name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    name: Build and test
    strategy:
      matrix:
        otp: ["24.2"]
        elixir: ["1.13.2"]
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build/test/*.plt
            _build/test/*.plt.hash
          key: ${{ runner.os }}-mix-test-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-test
      - name: Install dependencies
        run: MIX_ENV=test mix deps.get
      - name: Build
        run: MIX_ENV=test mix compile
      - name: Compliance check
        run: MIX_ENV=test mix credo
      - name: Dialyzer check
        run: MIX_ENV=test mix dialyzer
      - name: Tests
        run: MIX_ENV=test mix espec
